packageExtensions:
  'fastify-cors@*':
    peerDependencies:
      fastify: '*'
  '@nestjs/websockets@*':
    dependencies:
      '@nestjs/platform-socket.io': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/websockets': '*'
      reflect-metadata: '*'
      class-validator: '*'
  '@nestjs/common@*':
    dependencies:
      reflect-metadata: '*'
      class-validator: '*'
      class-transformer: '*'
      cache-manager: '*'
  '@nestjs/microservices@*':
    dependencies:
      reflect-metadata: '*'
      '@nestjs/websockets': '*'
    peerDependencies:
      rxjs: '*'
  typeorm@*:
    dependencies:
      sql.js: '*'
      sqlite3: '*'
  typesense@*:
    dependencies:
      '@babel/runtime': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - .yarn/plugins/@atls/plugin-essentials.cjs


yarnPath: .yarn/releases/yarn-3.0.2.cjs
